Add cross-compile support
sethforprivacy/simple-monerod-docker pull request #42
Opened 2022-05-08 02:03 UTC by theanonymousexyz

This PR adds cross-compile support via Docker Buildx and fixes #21.

2022-05-08 11:46 UTC, sethforprivacy commented
Wow, thank you so much for this, quite a large change and a huge step forward! Have you tested this on ARMv8 etc. to ensure it works for platforms other than amd64? I unfortunately don't have any Pi's etc. lying around to test on.

2022-05-08 12:55 UTC, theanonymousexyz commented
@sethforprivacy I need to make a few small fixes first, but after that I have a Raspberry Pi I can test it on.

Also, what do you think about supporting 32-bit systems, should we do that?

2022-05-08 21:31 UTC, theanonymousexyz commented
@sethforprivacy, confirmed working on a Raspberry Pi 4B, built with `--platform linux/arm64`:
![image](https://user-images.githubusercontent.com/26819407/167316617-315c6d78-1c8a-487f-b15f-fad687fa24d6.png)

2022-05-08 21:51 UTC, theanonymousexyz commented
@sethforprivacy It seems the CI fails on the ARMv7 (32-bit) build. Do you want me to remove it and only keep ARMv8 (64-bit)?

2022-05-09 12:08 UTC, sethforprivacy commented
Yeah, I wouldn't stress over 32-bit support as that's not a suitable platform for Monero nodes for the most part anyways as most ARMv7 SBCs lack AES support as well. ARMv8 is a big step forward and a huge blessin,g thank you so much for all of the time spent on this!

I'll do a full review today and likely squash + merge afterwards assuming I don't catch anything major.

2022-05-09 14:23 UTC, theanonymousexyz commented
Alright, I've removed `linux/arm` (ARMv7) from the workflows. If 32-bit systems don't support those features, then it's weird that `monerod` is even available for those platforms. They're officially supported in the `Makefile` at least.

Should be ready for merging now.

2022-05-09 17:08 UTC, sethforprivacy requested changes
Overall seems excellent! Just would love to hear why caching was removed, after that I think this is all set.

2022-05-09 17:08 UTC, sethforprivacy commented on .github/workflows/build-image-on-push.yml
> -          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:alpine
Why the cache removal? Did it break builds for some reason? Caching speeds up rebuilds quite a bit, so if possible would love to leave that in here.

2022-05-09 17:08 UTC, sethforprivacy commented on .github/workflows/update-image-on-push.yml
> -          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:latest
Why cache removal here as well?

2022-05-09 17:08 UTC, sethforprivacy commented on .github/workflows/update-ubuntu-image-on-push.yml
> -          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:ubuntu
Cache again :)

2022-05-09 18:32 UTC, theanonymousexyz commented on .github/workflows/build-image-on-push.yml
> -          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:alpine
Ah yes, forgot about that one. The build failed because Docker somehow couldn't figure out that the existing cache in the registry doesn't work for the extra architecture(s). I forgot to comment on that. It should work after the first push to Docker Hub though, so you should be able to re-add it after this PR is merged and the images are pushed for the first time.

2022-05-09 18:32 UTC, theanonymousexyz commented on .github/workflows/update-image-on-push.yml
> -          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:latest
Same as above.

2022-05-09 18:32 UTC, theanonymousexyz commented on .github/workflows/update-ubuntu-image-on-push.yml
> -          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:ubuntu
Same as above.

2022-05-09 18:52 UTC, sethforprivacy commented on .github/workflows/build-image-on-push.yml
> -          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:alpine
Perfect, will push and then PR the cache additions afterwards. Thanks again *so much* for contributing this!

2022-05-09 18:52 UTC, sethforprivacy approved these changes

2022-05-09 18:52 UTC, merged

2022-05-09 19:00 UTC, theanonymousexyz commented on .github/workflows/build-image-on-push.yml
> -          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/simple-monerod:alpine
@sethforprivacy I've done it. I'll open a PR when the workflows on `main` have finished.

2022-05-10 12:12 UTC, sethforprivacy commented
Hey @theanonymousexyz I had to revert, this broke all amd64 images and for some reason I didn't even think to test that yesterday. Please open a new PR and I will more thoroughly test it out, not sure what it was that broke it but my gut tells me it's the actual monerod compilation step not having a set platform.

2022-05-10 12:19 UTC, theanonymousexyz commented
Hmm, that's weird. I tested the `amd64` build on my system, where it worked fine. I'll take a look at it later today.

2022-05-10 12:34 UTC, sethforprivacy commented
It broke all my own nodes overnight as well once they pulled the image, exit code `132`. I haven't had time to dig in further, though.

2022-05-10 12:36 UTC, sethforprivacy commented
More here as well: https://github.com/sethforprivacy/simple-monerod-docker/issues/44

2022-05-10 12:38 UTC, theanonymousexyz commented
When I looked at the CMAKE script in the monerod repo, it looked like it automatically determines the architecture. But it might be because I removed `-D BUILD_64=ON` when I tried adding 32-bit support.

2022-05-10 12:41 UTC, sethforprivacy commented
TBQH I'm an absolute noob when it comes to CMAKE and I grabbed those args from an assortment of different places so that very well could be it.

I would think it wouldn't be required if the underlying arch is 64-bit, but I'm not sure at all.

2022-05-10 12:43 UTC, theanonymousexyz commented
> TBQH I'm an absolute noob when it comes to CMAKE

Yeah me too haha. I'll try it out later.